version: '1'

services:
  server:
    container_name: server
    image: lavida-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=server
    environment:
      - PORT=3001
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=3306
      - DATABASE_NAME=lavida
      - DATABASE_USERNAME=root
    expose:
      - 3306
    ports:
      - '3001:3001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
  judgeserver:
    container_name: judgeserver
    image: lavida-judgeserver
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=judgeserver
    env_file:
      - apps/judgeserver/.env
    environment:
      - PORT=3002
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=3306
      - DATABASE_NAME=lavida
      - DATABASE_USERNAME=root
    expose:
      - 3306
    ports:
      - '3002:3002'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=bTqVQB8uTaaDjHjmEJnnCA
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

volumes:
  kafka_data:
    driver: local
